### ISSUE TITLE
website link redirects to 404

### ISSUE THREAD

**Issue by iakkus** [serverlessworkflow/serverlessworkflow.github.io#1]
https://serverlessworkflow.io in the README.md redirects to https://cncf.github.io/wg-serverless-workflow/, which is not existing anymore.

It should be https://serverlessworkflow.github.io/.

**Comment by tsurdilo** [comment]
@iakkus thanks for submitting this request - the redirect change is in place, but it might take some hours before it propagates.

**Comment by tsurdilo** [comment]
@iakkus the redirect for serverlessworkflow.org seems to have kicked in already and works properly

**Comment by iakkus** [comment]
Yep, it works for me too. Thanks!

**Comment by tsurdilo** [comment]
@iakkus ok the redirect for serverlessworkflow.io seems to have kicked in. Is it ok to close this issue?
