### ISSUE TITLE
Site pointing to schema hosted in github

### ISSUE THREAD

**Issue by manick02** [serverlessworkflow/serverlessworkflow.github.io#140]
Site still points to schema hosted in github
https://github.com/serverlessworkflow/serverlessworkflow.github.io/blob/f20fc84e4cfe5bab521b83bea9459e4ffa6ee363/editor.html#L217
**What would you like to be added**:
It should be pointing schema hosted in the site

**Why is this needed**:

**Comment by tsurdilo** [comment]
thanks for finding this and for doing the PR!!! https://github.com/serverlessworkflow/serverlessworkflow.github.io/commit/e08c99dd85613c6ccf121b5c24b94e8a7901820c
