### ISSUE TITLE
Link to schemas

### ISSUE THREAD

**Issue by JBBianchi** [serverlessworkflow/serverlessworkflow.github.io#160]
**What would you like to be added**:
It seems the link to the specification's schemas don't exist anymore, it would be nice to have them.

**Why is this needed**:
1. They exist/are hosted on the website
2. It's the id used in the schemas
3. It would prevent the user from having to find them on GitHub.

**Comment by tsurdilo** [comment]
Feel free to do a pr that adds them to this repo readme: https://github.com/serverlessworkflow/serverlessworkflow.github.io/blob/main/README.md

we also have redirects in place for shortcuts (previous/latests/snapshot): https://github.com/serverlessworkflow/serverlessworkflow.github.io/blob/main/_redirects
