### ISSUE TITLE
Unable "unsafe" CORS

### ISSUE THREAD

**Issue by JBBianchi** [serverlessworkflow/serverlessworkflow.github.io#161]
**What would you like to be added**:
I would like to be o load the schemas form the website but CORS policies prevent me to do so. It would be nice to disable them.

**Why is this needed**:
For foreign sites to load the resources.

**Comment by antmendoza** [comment]
That makes sense to me. Everything on this site is static so there shouldn't be any problem I think.

**Comment by tsurdilo** [comment]
I believe you can do pr with a "_headers" file in this repo and set headers according to:

https://docs.netlify.com/routing/headers/#syntax-for-the-headers-file
https://answers.netlify.com/t/access-control-allow-origin-policy/1813
