### ISSUE TITLE
Execute your production workflows: add golang runtime

### ISSUE THREAD

**Issue by walterlife** [serverlessworkflow/serverlessworkflow.github.io#182]
**What would you like to be added**:
Request to add the Workflow Runtime implementation: [serverlessworkflow-go](https://github.com/apache/incubator-eventmesh/tree/master/eventmesh-workflow-go).

Project materials:
Project logo: https://sw-1251681900.cos.ap-singapore.myqcloud.com/em.png
Project name: EventMesh Workflow
Project Description: EventMesh Workflow is a cloud vendor-independent, cloud-native-oriented Serverless Workflow Runtime based on Serverless Workflow specification, and provides durability, reliability, scalability, and observability capabilities.

**Comment by JBBianchi** [comment]
I think this has been done and can be closed.

**Comment by cdavernas** [comment]
Closed as completed!
