### ISSUE TITLE
Move to Netlify

### ISSUE THREAD

**Issue by caniszczyk** [serverlessworkflow/serverlessworkflow.github.io#20]
1) move the site to Netlify so you can get PR previews

2) also take advantage of Netlify DNS

**Comment by ricardozanini** [comment]
@tsurdilo fyi

**Comment by msmagnanijr** [comment]
awesome!

**Comment by zacharysarah** [comment]
@ricardozanini @tsurdilo @msmagnanijr 

👋 Are you admins for the project? If not, who is?

I'm happy to walk you through creating a Netlify team and deployment. You need:
- Someone with admin access to the serverlessworkflow.github.io repo
- Someone with access to the project account's email to fill out [Netlify's open source plan application](https://opensource-form.netlify.com/)

Let me know when you've got these squared away!

**Comment by tsurdilo** [comment]
Hi @zacharysarah Chris Aniszczyk and myself have repo admin access. Ok, will look into this asap. Thanks

**Comment by tsurdilo** [comment]
@zacharysarah I have a question regarding:
"Someone with access to the project account's email to fill out Netlify's open source plan application"

This form wants us to have:

<img width="740" alt="Screen Shot 2020-10-26 at 12 46 59 PM" src="https://user-images.githubusercontent.com/119422/97201978-6bb64d80-1789-11eb-9974-2ecf8eaefd05.png">


So we need to put this link on our existing index page before we even get granted a license?

**Comment by caniszczyk** [comment]
@tsurdilo you should be invited to https://app.netlify.com/sites/serverless-workflow/overview

**Comment by zacharysarah** [comment]
@tsurdilo 
> So we need to put this link on our existing index page before we even get granted a license? Seems a little bit backwards

Looks like it's not necessary--the CNCF handles billing at the org level. Happy to be wrong about this one. 😄 

Another question: what custom domain would you like? serverless-workflow.io? .com?

**Comment by tsurdilo** [comment]
@zacharysarah 
we currently have

serverlessworkflow.io
serverlessworkflow.org

would like to keep those two if possible.

Thanks!

**Comment by tsurdilo** [comment]
@zacharysarah thats what I had questions on too :) Would you be able to set this up for us? I do not own the domain and @caniszczyk has helped us before to set up the redirect for serverlessworkflow.io/org to https://serverlessworkflow.github.io/

So how does this change our process, we still make changes here to the source and it will "magically" be picked up by Netlify and deployed there? Sorry never done this so I am confused.

**Comment by tsurdilo** [comment]
@caniszczyk thanks! got the email and logged in. Many thanks.

**Comment by zacharysarah** [comment]
@tsurdilo
> So how does this change our process, we still make changes here to the source and it will "magically" be picked up by Netlify and deployed there? 

Yes, basically. 

I've added serverlessworkflow.io and serverlessworkflow.org to the domain list. We need to repoint the DNS servers on the CNCF side--I've opened a ticket to do that now, and will keep you updated on progress.

**Comment by zacharysarah** [comment]
@tsurdilo 
1. serverlessworkflow.io is successfully aliased and using Netlify DNS: http://serverlessworkflow.io/ 

2. serverlessworkflow.org is successfully aliased and using Netlify DNS: http://serverlessworkflow.org/

**Comment by tsurdilo** [comment]
@zacharysarah just tested it. thank you! 
will try making a change (to add some kubecon links) and see if it gets picked up :)

**Comment by tsurdilo** [comment]
@zacharysarah oh wow you were right this just works now:

<img width="942" alt="Screen Shot 2020-10-26 at 7 10 46 PM" src="https://user-images.githubusercontent.com/119422/97238127-0715e580-17bf-11eb-8afd-aa02f74b8c7a.png">

Thanks again, you guys rock!!

**Comment by zacharysarah** [comment]
@tsurdilo Great! If you're happy, feel free to close this issue. 🙇

**Comment by ricardozanini** [comment]
@zacharysarah @tsurdilo can I have access to the Netlify account as well? We need to create a custom subdomain for the VSCode Plugin services. This custom endpoint will redirect to a custom shared service deployed in the cloud, so we can change the route anytime just changing the DNS without impacting our users. Many thanks!

**Comment by ricardozanini** [comment]
@tsurdilo @zacharysarah guys have you had the chance to take a look at the comment above? We really need to create the DNS entry to redirect to our services. Thanks!

**Comment by tsurdilo** [comment]
@ricardozanini i think with netlify we could try to deploy that service on netlify itself and make it part of the site. Maybe that would be something we could look at ?

**Comment by ricardozanini** [comment]
@tsurdilo not sure of netlify has the option to deploy an application in there. I haven't found any information about it... or I'm just too dumb to see. Can you give me access to the SW dashboard so I can take a look? As far as I understood, their service is related to DNS only, not a cloud provider itself.

**Comment by tsurdilo** [comment]
Closing issue (long overdue :)) Thank you for allowing us to host our website!
