### ISSUE TITLE
Links to lower sections from top nav e.g. 'what...' and 'contribute...' cloudevents.io

### ISSUE THREAD

**Issue by kitmacleod** [serverlessworkflow/serverlessworkflow.github.io#41]
**What would you like to be added**:
Links to lower sections from top nav e.g. 'what...' and 'contribute...'
**Why is this needed**:
A great design, key content could be easier to find.

**Comment by ricardozanini** [comment]
@kitmacleod you want to see the menu that we have here:

![Screenshot from 2020-12-10 13-17-36](https://user-images.githubusercontent.com/1538000/101798720-2efca680-3aea-11eb-906e-83c723f83bc8.png)

In here:

![Screenshot from 2020-12-10 13-17-54](https://user-images.githubusercontent.com/1538000/101798735-358b1e00-3aea-11eb-8c1e-ca20004970a6.png)

?

**Comment by kitmacleod** [comment]
Apologies @ricardozanini I was commented on the wrong site.
